In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
df.sample(5)

age  gender   review education purchased
9    74    Male     Good        UG       Yes
21   32    Male  Average        PG        No
31   22  Female     Poor    School       Yes
38   45  Female     Good    School        No
11   74    Male     Good        UG       Yes

In [5]:
df = df.iloc[:,2:]

In [6]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [18]:
from sklearn.model_selection import train_test_split

In [34]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1], test_size=0.2)

In [20]:
X_train

review education
5   Average    School
47     Good        PG
16     Poor        UG
1      Poor        UG
11     Good        UG
17     Poor        UG
36     Good        UG
32  Average        UG
9      Good        UG
2      Good        PG
49     Good        UG
30  Average        UG
28     Poor    School
10     Good        UG
12     Poor    School
35     Poor    School
44  Average        UG
21  Average        PG
23     Good    School
39     Poor        PG
27     Poor        PG
18     Good    School
48     Good        UG
7      Poor    School
45     Poor        PG
26     Poor        PG
29  Average        UG
41     Good        PG
34  Average    School
33     Good        PG
42     Good        PG
15     Poor        UG
31     Poor    School
22     Poor        PG
6      Good    School
40     Good    School
37  Average        PG
4   Average        UG
19     Poor        PG
13  Average    School

In [21]:
from sklearn.preprocessing import OrdinalEncoder

In [22]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [23]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [24]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [25]:
X_train

array([[1., 0.],
       [2., 2.],
       [0., 1.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [0., 1.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [1., 2.],
       [1., 1.],
       [0., 2.],
       [1., 0.]])

In [26]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [27]:
X_train

array([[1., 0.],
       [2., 2.],
       [0., 1.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [0., 1.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [1., 2.],
       [1., 1.],
       [0., 2.],
       [1., 0.]])

In [28]:
from sklearn.preprocessing import LabelEncoder

In [29]:
le = LabelEncoder()

In [30]:
le.fit(y_train)

LabelEncoder()

In [31]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [35]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [36]:
y_train

array([1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0])