In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed(23)

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

In [3]:
mu_vec1

array([0, 0, 0])

In [4]:
cov_mat1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [5]:
class1_sample

array([[ 0.66698806,  0.02581308, -0.77761941],
       [ 0.94863382,  0.70167179, -1.05108156],
       [-0.36754812, -1.13745969, -1.32214752],
       [ 1.77225828, -0.34745899,  0.67014016],
       [ 0.32227152,  0.06034293, -1.04345   ],
       [-1.00994188,  0.44173637,  1.12887685],
       [-1.83806777, -0.93876863, -0.20184052],
       [ 1.04537128,  0.53816197,  0.81211867],
       [ 0.2411063 , -0.95250953, -0.13626676],
       [ 1.26724821,  0.17363364, -1.22325477],
       [ 1.41531998,  0.45771098,  0.72887584],
       [ 1.96843473, -0.54778801, -0.67941827],
       [-2.50623032,  0.14696049,  0.60619549],
       [-0.02253889,  0.01342226,  0.93594489],
       [ 0.42062266,  0.41161964, -0.07132392],
       [-0.04543758,  1.04088597, -0.09403473],
       [-0.42084395, -0.55198856, -0.12109755],
       [ 0.19014136,  0.51213739,  0.13153847],
       [-0.33161712, -1.63238628,  0.61911407],
       [-0.99257378, -0.16134639,  1.19240433]])

In [6]:
class1_sample.shape

(20, 3)

In [7]:
df = pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target'] = 1

In [8]:
df

feature1  feature2  feature3  target
0   0.666988  0.025813 -0.777619       1
1   0.948634  0.701672 -1.051082       1
2  -0.367548 -1.137460 -1.322148       1
3   1.772258 -0.347459  0.670140       1
4   0.322272  0.060343 -1.043450       1
5  -1.009942  0.441736  1.128877       1
6  -1.838068 -0.938769 -0.201841       1
7   1.045371  0.538162  0.812119       1
8   0.241106 -0.952510 -0.136267       1
9   1.267248  0.173634 -1.223255       1
10  1.415320  0.457711  0.728876       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1
13 -0.022539  0.013422  0.935945       1
14  0.420623  0.411620 -0.071324       1
15 -0.045438  1.040886 -0.094035       1
16 -0.420844 -0.551989 -0.121098       1
17  0.190141  0.512137  0.131538       1
18 -0.331617 -1.632386  0.619114       1
19 -0.992574 -0.161346  1.192404       1

In [9]:
mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

In [10]:
df1

feature1  feature2  feature3  target
0   1.250737  0.186384  1.703624       0
1   0.731858  0.517441  2.244610       0
2   1.676860  4.187503 -0.080565       0
3   1.010229  1.437830  2.327788       0
4   0.748855  2.593111  1.170818       0
5   0.290746  0.866975  0.982643       0
6   0.898907  0.435960  0.820964       0
7   2.011059  1.920996  2.933090       0
8   0.204637 -0.011535  3.150780       0
9   1.425140  1.441152  0.182561       0
10  1.437892  1.099723  1.065406       0
11  2.224431  0.230401  1.192120       0
12 -0.723253  1.461259 -0.085367       0
13  2.823378 -0.332863  2.637391       0
14  0.177061 -0.598109  1.226512       0
15  1.233898  0.052778 -0.261576       0
16 -1.389866  0.666726  1.343517       0
17 -1.027861  1.131416  2.603234       0
18 -0.764314  1.566504  1.548788       0
19  0.384865  1.323546 -0.103193       0

In [11]:
df = df.append(df1,ignore_index=True)

df = df.sample(40)

<ipython-input-11-e36ad133e6cb>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(df1,ignore_index=True)


In [12]:
df

feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1
29  1.425140  1.441152  0.182561       0
31  2.224431  0.230401  1.192120       0
4   0.322272  0.060343 -1.043450       1
32 -0.723253  1.461259 -0.085367       0
33  2.823378 -0.332863  2.637391       0
36 -1.389866  0.666726  1.343517       0
18 -0.331617 -1.632386  0.619114       1
0   0.666988  0.025813 -0.777619       1
5  -1.009942  0.441736  1.128877       1
39  0.384865  1.323546 -0.103193       0
22  1.676860  4.187503 -0.080565       0
8   0.241106 -0.952510 -0.136267       1
15 -0.045438  1.040886 -0.094035       1
19 -0.992574 -0.161346  1.192404       1
30  1.437892  1.099723  1.065406       0
25  0.290746  0.866975  0.982643       0
21  0.731858  0.517441  2.244610       0
37 -1.027861  1.131416  2.603234       0
16 -0.420844 -0.551989 -0.121098       1
38 -0.764314  1.566504  1.548788       0
27  2.011059  1.920996  2.933090       0
26  0.898907  0.435960  0.820964       0
23  1.010229  1.437830  2.327788       0
1   0.948634  0.701672 -1.051082       1
10  1.415320  0.457711  0.728876       1
20  1.250737  0.186384  1.703624       0
28  0.204637 -0.011535  3.150780       0
24  0.748855  2.593111  1.170818       0
7   1.045371  0.538162  0.812119       1
6  -1.838068 -0.938769 -0.201841       1
17  0.190141  0.512137  0.131538       1
13 -0.022539  0.013422  0.935945       1
9   1.267248  0.173634 -1.223255       1
35  1.233898  0.052778 -0.261576       0
3   1.772258 -0.347459  0.670140       1

In [13]:
df.shape

(40, 4)

In [14]:
df.head()

feature1  feature2  feature3  target
2  -0.367548 -1.137460 -1.322148       1
34  0.177061 -0.598109  1.226512       0
14  0.420623  0.411620 -0.071324       1
11  1.968435 -0.547788 -0.679418       1
12 -2.506230  0.146960  0.606195       1

In [15]:
import plotly.express as px
#y_train_trf = y_train.astype(str)
fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
              color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()

In [16]:
# Step 1 - Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [19]:
df.describe()

feature1      feature2      feature3    target
count  4.000000e+01  4.000000e+01  4.000000e+01  40.00000
mean   1.110223e-17  1.776357e-16 -9.992007e-17   0.50000
std    1.012739e+00  1.012739e+00  1.012739e+00   0.50637
min   -2.571350e+00 -1.998011e+00 -1.749156e+00   0.00000
25%   -6.772394e-01 -4.866010e-01 -6.815652e-01   0.00000
50%   -2.709371e-02 -3.531748e-02  2.798692e-02   0.50000
75%    7.181907e-01  5.677633e-01  4.687647e-01   1.00000
max    2.090049e+00  3.557281e+00  2.182786e+00   1.00000

In [20]:
# Step 2 - Find Covariance Matrix
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


In [21]:
# Step 3 - Finding EV and EVs
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [22]:
eigen_values

array([1.3536065 , 0.94557084, 0.77774573])

In [23]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [36]:
%pylab inline

from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d import proj3d
from matplotlib.patches import FancyArrowPatch


class Arrow3D(FancyArrowPatch):
    def __init__(self, xs, ys, zs, *args, **kwargs):
        FancyArrowPatch.__init__(self, (0,0), (0,0), *args, **kwargs)
        self._verts3d = xs, ys, zs

    def draw(self, renderer):
        xs3d, ys3d, zs3d = self._verts3d
        xs, ys, zs = proj3d.proj_transform(xs3d, ys3d, zs3d, renderer.M)
        self.set_positions((xs[0],ys[0]),(xs[1],ys[1]))
        FancyArrowPatch.draw(self, renderer)

fig = plt.figure(figsize=(7,7))
ax = fig.add_subplot(111, projection='3d')
ax.plot(df['feature1'], df['feature2'], df['feature3'], 'o', markersize=8, color='blue', alpha=0.2)
ax.plot([df['feature1'].mean()], [df['feature2'].mean()], [df['feature3'].mean()], 'o', markersize=10, color='red', alpha=0.5)

for v in eigen_vectors.T:
  a = Arrow3D([df['feature1'].mean(), v[0]], [df['feature2'].mean(), v[1]], [df['feature3'].mean(), v[2]], mutation_scale=20, lw=3, arrowstyle="-|>", color="r")
  ax.add_artist(a)
  ax.set_xlabel('x_values')
  ax.set_ylabel('y_values')
  ax.set_zlabel('z_values')
  plt.title('Eigenvectors')

plt.show()

Populating the interactive namespace from numpy and matplotlib


AttributeError: ignored

<Figure size 700x700 with 1 Axes>

In [27]:
pc = eigen_vectors[0:2]
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [28]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)
# 40,3 - 3,2
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()

PC1       PC2  target
0  0.599433  1.795862       1
1  1.056919 -0.212737       0
2 -0.271876  0.498222       1
3 -0.621586  0.023110       1
4  1.567286  1.730967       1

In [29]:
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['PC1'],
                 y=new_df['PC2'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()