In [3]:
para = """Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ; born 17 September 1950)[b] is an Indian politician who has served as the 14th prime minister of India since May 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right wing Hindu nationalist paramilitary volunteer organisation. He is the longest-serving prime minister from outside the Indian National Congress.

Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated. At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time worker for the RSS in Gujarat in 1971. The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank of general secretary."""


In [4]:
para

'Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ; born 17 September 1950)[b] is an Indian politician who has served as the 14th prime minister of India since May 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right wing Hindu nationalist paramilitary volunteer organisation. He is the longest-serving prime minister from outside the Indian National Congress.\n\nModi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated. At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time w

In [5]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

Tokenization -->convert Paragraph-Sntence to Words

In [6]:
nltk.download('punkt')
sen = nltk.sent_tokenize(para)
sen

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Strimmerz\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ; born 17 September 1950)[b] is an Indian politician who has served as the 14th prime minister of India since May 2014.',
 'Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi.',
 'He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right wing Hindu nationalist paramilitary volunteer organisation.',
 'He is the longest-serving prime minister from outside the Indian National Congress.',
 'Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education.',
 'He was introduced to the RSS at the age of eight.',
 'His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated.',
 'At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so.

In [7]:
sen[5]

'He was introduced to the RSS at the age of eight.'

In [8]:
len(sen)

10

Steaming --> convert -->base word

In [9]:
steam = PorterStemmer()
steam.stem('going')

'go'

In [10]:
steam.stem('history')


'histori'

In [11]:
steam.stem('thinking')


'think'

In [12]:
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Strimmerz\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [13]:
lemmat = WordNetLemmatizer()

In [14]:
lemmat.lemmatize('history')

'history'

In [15]:
import re

In [16]:
corpus = []
for i in range(len(sen)):
    review = re.sub('[^a-zA-z]',' ',sen[i])
    review = review.lower()
    corpus.append(review)   

In [17]:
corpus

['narendra damodardas modi  gujarati  [ n  end   d mod   d s  modi ]    born    september      [b] is an indian politician who has served as the   th prime minister of india since may      ',
 'modi was the chief minister of gujarat from      to      and is the member of parliament  mp  for varanasi ',
 'he is a member of the bharatiya janata party  bjp  and of the rashtriya swayamsevak sangh  rss   a right wing hindu nationalist paramilitary volunteer organisation ',
 'he is the longest serving prime minister from outside the indian national congress ',
 'modi was born and raised in vadnagar in northeastern gujarat  where he completed his secondary education ',
 'he was introduced to the rss at the age of eight ',
 'his account of helping his father sell tea at the vadnagar railway station has not been reliably corroborated ',
 'at age     he was married to jashodaben modi  whom he abandoned soon after  only publicly acknowledging her four decades later when legally required to do so 

In [18]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Strimmerz\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [19]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [20]:
##steamming
for i in corpus:
    words = nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(steam.stem(word))

narendra
damodarda
modi
gujarati
[
n
end
mod
modi
]
born
septemb
[
b
]
indian
politician
serv
th
prime
minist
india
sinc
may
modi
chief
minist
gujarat
member
parliament
mp
varanasi
member
bharatiya
janata
parti
bjp
rashtriya
swayamsevak
sangh
rss
right
wing
hindu
nationalist
paramilitari
volunt
organis
longest
serv
prime
minist
outsid
indian
nation
congress
modi
born
rais
vadnagar
northeastern
gujarat
complet
secondari
educ
introduc
rss
age
eight
account
help
father
sell
tea
vadnagar
railway
station
reliabl
corrobor
age
marri
jashodaben
modi
abandon
soon
publicli
acknowledg
four
decad
later
legal
requir
modi
becam
full
time
worker
rss
gujarat
rss
assign
bjp
held
sever
posit
within
parti
hierarchi
rise
rank
gener
secretari


In [21]:
##Lemmatizer
for i in corpus:
    words = nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(lemmat.lemmatize(word))

narendra
damodardas
modi
gujarati
[
n
end
mod
modi
]
born
september
[
b
]
indian
politician
served
th
prime
minister
india
since
may
modi
chief
minister
gujarat
member
parliament
mp
varanasi
member
bharatiya
janata
party
bjp
rashtriya
swayamsevak
sangh
r
right
wing
hindu
nationalist
paramilitary
volunteer
organisation
longest
serving
prime
minister
outside
indian
national
congress
modi
born
raised
vadnagar
northeastern
gujarat
completed
secondary
education
introduced
r
age
eight
account
helping
father
sell
tea
vadnagar
railway
station
reliably
corroborated
age
married
jashodaben
modi
abandoned
soon
publicly
acknowledging
four
decade
later
legally
required
modi
became
full
time
worker
r
gujarat
r
assigned
bjp
held
several
position
within
party
hierarchy
rising
rank
general
secretary


In [22]:
#Bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(binary=True, ngram_range=(3,3))

In [23]:
x = cv.fit_transform(corpus)

In [24]:
x

<10x166 sparse matrix of type '<class 'numpy.int64'>'
	with 166 stored elements in Compressed Sparse Row format>

In [25]:
cv.vocabulary_

{'narendra damodardas modi': 86,
 'damodardas modi gujarati': 25,
 'modi gujarati end': 81,
 'gujarati end mod': 36,
 'end mod modi': 27,
 'mod modi born': 78,
 'modi born september': 80,
 'born september is': 22,
 'september is an': 121,
 'is an indian': 63,
 'an indian politician': 6,
 'indian politician who': 61,
 'politician who has': 103,
 'who has served': 161,
 'has served as': 38,
 'served as the': 122,
 'as the th': 11,
 'the th prime': 143,
 'th prime minister': 129,
 'prime minister of': 106,
 'minister of india': 77,
 'of india since': 93,
 'india since may': 59,
 'modi was the': 83,
 'was the chief': 158,
 'the chief minister': 133,
 'chief minister of': 23,
 'minister of gujarat': 76,
 'of gujarat from': 91,
 'gujarat from to': 34,
 'from to and': 32,
 'to and is': 146,
 'and is the': 8,
 'is the member': 66,
 'the member of': 136,
 'member of parliament': 73,
 'of parliament mp': 94,
 'parliament mp for': 100,
 'mp for varanasi': 85,
 'he is member': 42,
 'is member of':

In [26]:
corpus[0]

'narendra damodardas modi  gujarati  [ n  end   d mod   d s  modi ]    born    september      [b] is an indian politician who has served as the   th prime minister of india since may      '

In [27]:
x[0].toarray()

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]], dtype=int64)

In [28]:
##Applying Stopwords lemmatize

corpus=[]
for i in range(len(sen)):
    review = re.sub('[^a-zA-Z]',' ', sen[i])
    review = review.lower()
    review = review.split()
    review = [lemmat.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [29]:
x = cv.fit_transform(corpus)

In [30]:
x

<10x82 sparse matrix of type '<class 'numpy.int64'>'
	with 82 stored elements in Compressed Sparse Row format>

In [31]:
cv.vocabulary_

{'narendra damodardas modi': 47,
 'damodardas modi gujarati': 13,
 'modi gujarati end': 46,
 'gujarati end mod': 21,
 'end mod modi': 15,
 'mod modi born': 40,
 'modi born september': 44,
 'born september indian': 10,
 'september indian politician': 68,
 'indian politician served': 28,
 'politician served th': 55,
 'served th prime': 69,
 'th prime minister': 76,
 'prime minister india': 57,
 'minister india since': 38,
 'india since may': 26,
 'modi chief minister': 45,
 'chief minister gujarat': 11,
 'minister gujarat member': 37,
 'gujarat member parliament': 20,
 'member parliament mp': 36,
 'parliament mp varanasi': 52,
 'member bharatiya janata': 35,
 'bharatiya janata party': 6,
 'janata party bjp': 30,
 'party bjp rashtriya': 53,
 'bjp rashtriya swayamsevak': 8,
 'rashtriya swayamsevak sangh': 63,
 'swayamsevak sangh right': 74,
 'sangh right wing': 66,
 'right wing hindu': 64,
 'wing hindu nationalist': 80,
 'hindu nationalist paramilitary': 25,
 'nationalist paramilitary volu

In [32]:
x[0].toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
        1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=int64)

TF - IDF --- Term Frequency - Inverse Document Frequency

In [53]:
#TF_IDF
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(ngram_range=(1,1), max_features=10)
X = cv.fit_transform(corpus)
X
print(X[0])

  (0, 5)	0.36589482798903955
  (0, 8)	0.4182219977592325
  (0, 3)	0.4182219977592325
  (0, 1)	0.4182219977592325
  (0, 6)	0.5842876488697163


In [54]:
print(len(corpus[0]))
corpus[0]

124


'narendra damodardas modi gujarati n end mod modi born september b indian politician served th prime minister india since may'

In [55]:
X[0]

<1x10 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [56]:
X[0].toarray()

array([[0.        , 0.418222  , 0.        , 0.418222  , 0.        ,
        0.36589483, 0.58428765, 0.        , 0.418222  , 0.        ]])