### Word Embedding Techniques using Embedding Layer in Keras

In [3]:
### Libraries USed Tensorflow> 2.0  and keras

In [4]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [5]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [10]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[43, 325, 242, 221], [43, 325, 242, 465], [43, 367, 242, 263], [41, 5, 188, 81, 207], [41, 5, 188, 81, 351], [86, 43, 126, 242, 174], [439, 364, 382, 81]]


### Word Embedding Represntation

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  43 325 242 221]
 [  0   0   0   0  43 325 242 465]
 [  0   0   0   0  43 367 242 263]
 [  0   0   0  41   5 188  81 207]
 [  0   0   0  41   5 188  81 351]
 [  0   0   0  86  43 126 242 174]
 [  0   0   0   0 439 364 382  81]]


In [14]:
## 10 feature dimesnions
dim=10


In [15]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0,  43, 325, 242, 221], dtype=int32)

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 110ms/step


array([[ 0.04828974, -0.03848653, -0.03603994, -0.01849815, -0.00209443,
         0.02372131,  0.02765462,  0.02210325,  0.00086595, -0.04292622],
       [ 0.04828974, -0.03848653, -0.03603994, -0.01849815, -0.00209443,
         0.02372131,  0.02765462,  0.02210325,  0.00086595, -0.04292622],
       [ 0.04828974, -0.03848653, -0.03603994, -0.01849815, -0.00209443,
         0.02372131,  0.02765462,  0.02210325,  0.00086595, -0.04292622],
       [ 0.04828974, -0.03848653, -0.03603994, -0.01849815, -0.00209443,
         0.02372131,  0.02765462,  0.02210325,  0.00086595, -0.04292622],
       [-0.00263055, -0.00084464,  0.00120791,  0.00998646,  0.047118  ,
        -0.00103116,  0.0125807 , -0.03972007,  0.03262189, -0.03014679],
       [-0.02648751, -0.01317662,  0.03987939, -0.00828556, -0.03915594,
         0.04989227,  0.02129606,  0.01130732, -0.00186759,  0.01063336],
       [ 0.01463809,  0.01994319,  0.00835812,  0.01615855, -0.02220309,
         0.01593569,  0.00652249, -0.03322305

In [19]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 35ms/step
[[[ 0.04828974 -0.03848653 -0.03603994 -0.01849815 -0.00209443
    0.02372131  0.02765462  0.02210325  0.00086595 -0.04292622]
  [ 0.04828974 -0.03848653 -0.03603994 -0.01849815 -0.00209443
    0.02372131  0.02765462  0.02210325  0.00086595 -0.04292622]
  [ 0.04828974 -0.03848653 -0.03603994 -0.01849815 -0.00209443
    0.02372131  0.02765462  0.02210325  0.00086595 -0.04292622]
  [ 0.04828974 -0.03848653 -0.03603994 -0.01849815 -0.00209443
    0.02372131  0.02765462  0.02210325  0.00086595 -0.04292622]
  [-0.00263055 -0.00084464  0.00120791  0.00998646  0.047118
   -0.00103116  0.0125807  -0.03972007  0.03262189 -0.03014679]
  [-0.02648751 -0.01317662  0.03987939 -0.00828556 -0.03915594
    0.04989227  0.02129606  0.01130732 -0.00186759  0.01063336]
  [ 0.01463809  0.01994319  0.00835812  0.01615855 -0.02220309
    0.01593569  0.00652249 -0.03322305 -0.01204431  0.0066689 ]
  [ 0.03905005  0.03979519 -0.00760267  0.03275179 -0.0385804

In [20]:
embedded_docs[0]

array([  0,   0,   0,   0,  43, 325, 242, 221], dtype=int32)

In [21]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 18ms/step
[[ 0.04828974 -0.03848653 -0.03603994 -0.01849815 -0.00209443  0.02372131
   0.02765462  0.02210325  0.00086595 -0.04292622]
 [ 0.04828974 -0.03848653 -0.03603994 -0.01849815 -0.00209443  0.02372131
   0.02765462  0.02210325  0.00086595 -0.04292622]
 [ 0.04828974 -0.03848653 -0.03603994 -0.01849815 -0.00209443  0.02372131
   0.02765462  0.02210325  0.00086595 -0.04292622]
 [ 0.04828974 -0.03848653 -0.03603994 -0.01849815 -0.00209443  0.02372131
   0.02765462  0.02210325  0.00086595 -0.04292622]
 [-0.00263055 -0.00084464  0.00120791  0.00998646  0.047118   -0.00103116
   0.0125807  -0.03972007  0.03262189 -0.03014679]
 [-0.02648751 -0.01317662  0.03987939 -0.00828556 -0.03915594  0.04989227
   0.02129606  0.01130732 -0.00186759  0.01063336]
 [ 0.01463809  0.01994319  0.00835812  0.01615855 -0.02220309  0.01593569
   0.00652249 -0.03322305 -0.01204431  0.0066689 ]
 [ 0.03905005  0.03979519 -0.00760267  0.03275179 -0.0385804   0.0080152


In [22]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]