In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2)) #2-->input 2 -- > input node
model.add(Dense(1, activation='linear')) #1-->hidden node


In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
model.get_weights()

[array([[ 0.64190733, -0.6840347 ],
        [ 0.8738333 , -0.9189544 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.0851907 ],
        [ 0.17755759]], dtype=float32),
 array([0.], dtype=float32)]

In [10]:
new_weights = [np.array([[0.1,0.1], [0.1,0.1]], dtype=np.float32),
               np.array([0.,0.], dtype=np.float32),
               np.array([[0.1],[0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [11]:
model.set_weights(new_weights)

In [12]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [13]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [15]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 0s 5ms/step - loss: 26.2047
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 25.8490
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 25.4639
Epoch 4/75
4/4 [==============================] - 0s 4ms/step - loss: 25.0913
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 24.6813
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 24.2617
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 23.8349
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 23.3731
Epoch 9/75
4/4 [==============================] - 0s 6ms/step - loss: 22.9357
Epoch 10/75
4/4 [==============================] - 0s 5ms/step - loss: 22.5108
Epoch 11/75
4/4 [==============================] - 0s 5ms/step - loss: 22.0162
Epoch 12/75
4/4 [==============================] - 0s 6ms/step - loss: 21.5752
Epoch 13/75
4/4 [==============================] - 0s 5ms/ste

In [16]:
model.get_weights()

[array([[0.37912074, 0.37912074],
        [0.37296754, 0.37296754]], dtype=float32),
 array([0.279017, 0.279017], dtype=float32),
 array([[0.37973666],
        [0.37973666]], dtype=float32),
 array([0.2084756], dtype=float32)]