In [ ]:
import numpy as np
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [ ]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
len(tokenizer.word_index)

17

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [ ]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [7]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [8]:
model = Sequential()
model.add(Embedding(17, 2,input_length=5))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 5, 2)              34        
                                                                 
Total params: 34 (136.00 Byte)
Trainable params: 34 (136.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile('adam','accuracy')

In [ ]:
pred = model.predict(sequences)
print(pred)

1/1 [==============================] - 0s 119ms/step
[[[ 0.01685096  0.03196034]
  [-0.02691959  0.04478614]
  [ 0.00150258  0.0169353 ]
  [ 0.00150258  0.0169353 ]
  [ 0.00150258  0.0169353 ]]

 [[-0.02691959  0.04478614]
  [-0.02691959  0.04478614]
  [ 0.00150258  0.0169353 ]
  [ 0.00150258  0.0169353 ]
  [ 0.00150258  0.0169353 ]]

 [[-0.00252839 -0.02882034]
  [-0.00252839 -0.02882034]
  [-0.0311609  -0.02610534]
  [ 0.00150258  0.0169353 ]
  [ 0.00150258  0.0169353 ]]

 [[-0.04759225 -0.02303523]
  [ 0.04465327 -0.00792638]
  [-0.04759225 -0.02303523]
  [-0.02691959  0.04478614]
  [-0.04759225 -0.02303523]]

 [[ 0.0407221  -0.00893257]
  [-0.01624156  0.01145945]
  [ 0.006719   -0.03211103]
  [ 0.04819561 -0.04522149]
  [ 0.00150258  0.0169353 ]]

 [[ 0.04527588 -0.03892466]
  [ 0.04527588 -0.03892466]
  [ 0.00150258  0.0169353 ]
  [ 0.00150258  0.0169353 ]
  [ 0.00150258  0.0169353 ]]

 [[-0.03378262 -0.03074203]
  [-0.03378262 -0.03074203]
  [ 0.00150258  0.0169353 ]
  [ 0.00150

In [9]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [10]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [11]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [12]:
X_train.shape

(25000, 50)

In [13]:
model = Sequential()
model.add(Embedding(10000,2,input_length=50))
#model.add(Flatten())
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 32)                1120      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 21153 (82.63 KB)
Trainable params: 21153 (82.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
history = model.fit(X_train, y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 57s 71ms/step - loss: 0.5688 - accuracy: 0.6805 - val_loss: 0.4332 - val_accuracy: 0.7997
Epoch 2/5
782/782 [==============================] - 43s 55ms/step - loss: 0.3752 - accuracy: 0.8383 - val_loss: 0.4159 - val_accuracy: 0.8115
Epoch 3/5
782/782 [==============================] - 42s 54ms/step - loss: 0.3154 - accuracy: 0.8733 - val_loss: 0.4332 - val_accuracy: 0.8079
Epoch 4/5
782/782 [==============================] - 42s 54ms/step - loss: 0.2819 - accuracy: 0.8894 - val_loss: 0.4425 - val_accuracy: 0.8034
Epoch 5/5
782/782 [==============================] - 41s 52ms/step - loss: 0.2544 - accuracy: 0.9038 - val_loss: 0.4891 - val_accuracy: 0.7955


In [ ]:
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Embedding, Flatten, Dense
from keras.preprocessing import sequence

# Load the IMDb dataset
max_features = 10000  # Consider only the top 10,000 most frequent words
maxlen = 100  # Cut texts after this number of words in a review
batch_size = 32

print('Loading data...')
(input_train, y_train), (input_test, y_test) = imdb.load_data(num_words=max_features)
print(len(input_train), 'train sequences')
print(len(input_test), 'test sequences')

# Pad sequences to a fixed length
print('Pad sequences (samples x time)')
input_train = sequence.pad_sequences(input_train, maxlen=maxlen)
input_test = sequence.pad_sequences(input_test, maxlen=maxlen)
print('input_train shape:', input_train.shape)
print('input_test shape:', input_test.shape)

# Create the model
model = Sequential()

# Add an Embedding layer
model.add(Embedding(input_dim=max_features, output_dim=8, input_length=maxlen))

# Flatten the 3D tensor to 2D for the Dense layer
model.add(Flatten())

# Add a Dense layer
model.add(Dense(units=1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Display the model summary
model.summary()

# Train the model
history = model.fit(input_train, y_train, epochs=10, batch_size=batch_size, validation_split=0.2)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(input_test, y_test, batch_size=batch_size)
print(f'Test loss: {loss:.4f}, Test accuracy: {accuracy:.4f}')


Loading data...
25000 train sequences
25000 test sequences
Pad sequences (samples x time)
input_train shape: (25000, 100)
input_test shape: (25000, 100)
Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_8 (Embedding)     (None, 100, 8)            80000     
                                                                 
 flatten (Flatten)           (None, 800)               0         
                                                                 
 dense_2 (Dense)             (None, 1)                 801       
                                                                 
Total params: 80801 (315.63 KB)
Trainable params: 80801 (315.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/10
625/625 [==============================] - 2s 3ms/step - loss: 0.5948 - accuracy: 0.6950 - val_loss: 0.4192 - val_ac